### ISSUE TITLE
Host Scripts locally instead of loading from github

### ISSUE THREAD

**Issue by Codel1417** [maxwroc/battery-state-card#256]
**Is your feature request related to a problem? Please describe.**
Whenever this card is loaded it uses resources from github. specifically the contents of https://github.com/maxwroc/battery-state-card/tree/master/src are loaded externally. 

**Describe the solution you'd like**
I would like the scripts to be included with the hacs install and loaded from homeassistant instead of github

**Additional context**

**Comment by maxwroc** [comment]
What browser do you use? These files shouldn't be downloaded by default!

### Why these files are downloaded?
These resources shouldn't be downloaded unless you open browser dev tools. These additional files are for debugging purposes only.

### Why are they needed?
The original card code is written in TypeScript so it has to be transpiled to JS (which is making it less readable) and additionally it is minified at the end (which is making it not readable at all but in the same time it improves the downloading/parsing speed). 

### How does it work?
Every release contains JS and MAP file. Map file contains mapping from JS to TypeScript. It contains as well links to source code (TS files) located on the Github. This is how browser knows what to download.

 ### Why the card code has to be in a "debuggable" form?
It doesn't but I do it because of the following reasons:
* Transparency
  Card code is minified - not readable at all. I want to give the ability for people to review it. When the code is in such "obfuscated" form people may be considered that I'm releasing some malicious functions (bitcoin mining scripts etc ;) ). This way they can easier verify it.
* Easier debugging 
  If you know TypeScript/JavaScript and you spot the bug in the card you can easily debug it and fix it (send PR).

**Comment by Codel1417** [comment]
I didn't know that's how .map files work.
