### ISSUE TITLE
Can we filter by Area?

### ISSUE THREAD

**Issue by joaldes** [maxwroc/battery-state-card#263]
**Describe what is wrong**
I'm curious if this card supports filtering by Area?  I built the below, but am unsure if I'm doing something wrong if it's simply not supported.  I'm pretty new to lovelace and cards so I'm sorry if this is a dumb question.

**YAML configuration**
```type: 'custom:battery-state-card'
title: Filters
sort_by_entity_id: "asc"
bulk_rename:
  - from: "Battery" # simple string replace (note: "to" is not required if you want to remove string)
#    to: "sensor"
#  - from: "/\\s(temperature|temp)\\s/" # regular expression
#    to: " temp. "

filter:
  include: # filters for auto-adding
    - name: entity_id # entities which id ends with "_battery_level"
      value: "*_battery"
      area: "Master Bedroom"
#    - name: attributes.device_class # and entities which device_class attribute equals "battery"
#      value: battery
#      area: "Master Bedroom"
```

**Version**
1.6.4

**Comment by maxwroc** [comment]
No. All the supported features are listed in the documentation. 

Since the idea is interesting I'm changing it to "enchancement" proposal

**Comment by joaldes** [comment]
Thanks for the quick reply, at least I know I'm not crazy.  

I think it would be a pretty helpful filter to be able to include, so we wouldn't have to list entities explicitly and new devices would show up automatically.

Thanks for the very thorough examples you have, too, they are really helping me a lot!

**Comment by maxwroc** [comment]
I have investigated it and so far I have no idea how to get the areas data. I don't see it anywhere in the HA state provided for the cards. I'm closing it for now

**Comment by maxwroc** [comment]
Since we have now the new "native" area card I have taken a look at its code. There is a way to get the area info but the logic is rather complex and it requires to get such data via HA websocket.

I'm adding here this info just in case in the furure I (or someone else) decide to add the support for areas. But for now I think it doesn't make sense to add a big chunk of code just to have such functionality. Maybe at some point HA team will decide to stamp the entities with the area info (or it will be passed in some other way in the state object to all the cards).

Here is the change in which the area card was added
https://github.com/home-assistant/frontend/commit/4684979ae7f15504d6d900b021604f658170ff42#diff-d30b7fd25b1ed3d7a32681b3c781d194dfb010cf9f044d3500cb6fa9dd592d31

**Comment by maxwroc** [comment]
#253 Linking related request
