### ISSUE TITLE
Ability to add a custom "Unknown" icon color and change "unknown" to "Unknown"

### ISSUE THREAD

**Issue by SeLLeRoNe** [maxwroc/battery-state-card#33]
**Is your feature request related to a problem? Please describe.**
The unknown default icon color is to "light" compared to the customized color I use, it would be nice to have it customizable. 
Also, the value for might be "nicer" to be "Unknown" rather than "Unkonown"

**Describe the solution you'd like**
Have the ability to use "value: "unknown"" to define a custom color in the color_threshold
Default text to be Unknown instead of unknown.

**Additional context**

My current customizations:
![image](https://user-images.githubusercontent.com/9599441/80893468-dd2dab80-8cd2-11ea-838d-6fac9e60f924.png)

Battery card:
![image](https://user-images.githubusercontent.com/9599441/80893464-d56e0700-8cd2-11ea-8bd6-e2a990369394.png)

**Comment by maxwroc** [comment]
The "unknown" text which you see comes from your sensor, not from the card so I'm not going to change it. Though in the next minor ver update I have started upper casing the first letter of the state. I think this should cover your case.

Regarding the color: the difference is very small but I'll think about it... since other colors are configurable why not to make this one as well...

Leaving open for now. Once I finish other more important updates I'll work on this one. Meanwhile feel free to do this change yourself and submit PR ;)

**Comment by SeLLeRoNe** [comment]
Unfortunately I am not that good on developing, otherwise I would have done it ^^
I help the way I can, feedback and suggestions is what I can do best since there is no sysadmin work involved which is where I shine :D

**Comment by vampik** [comment]
> The "unknown" text which you see comes from your sensor, not from the card so I'm not going to change it.

Standard card shows the localized text, but battery-state-card shows "Unknown" instead of the localized text.

This may be related to the changes in 109.0 (another plugins are broken in the same manner).

**Comment by maxwroc** [comment]
You can adjust the color of items where the state is text (not a number) via custom styles:
```yaml
style: |
  .entity-row.non-numeric-state .icon {
    color: red;
  }
```

@vampik Meanwhile between my last comment here (where I was saying that "Unknown" text does not come from this card but sensor) and your comment I have actually added such level state (for the cases when the state was actually unknown). This text was not localized as you have noticed. I have fixed it in the latest release.
