### ISSUE TITLE
Do not render card if there are no entities to show

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#359]
**Describe the bug**

Card renders without entities

**How to reproduce**

Empty entity list or filter which hides batteries above the threshold

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config

```

**Screenshots**

**Version**

**Comment by ScottG489** [comment]
Hey @maxwroc thanks for this fix! However, it looks like the card is still displayed partially. I believe we should apply a `display: none` style to the card. See `auto-entities` for comparison:

<img width="421" alt="Screen Shot 2022-12-23 at 12 53 57 PM" src="https://user-images.githubusercontent.com/910809/209383649-0721c45a-8798-4688-a759-bdb7b849fd74.png">

You can see the battery card next to another card with the element highlighted in dev tools:

<img width="403" alt="Screen Shot 2022-12-23 at 12 55 11 PM" src="https://user-images.githubusercontent.com/910809/209384008-3e385e44-f0fc-4596-97a9-322ab6c101d8.png">

That part highlighted in orange is due to a 4 pixel margin on the top and bottom. Small nitpick of course, but it adds a noticeable gap when nested between other cards.

Note that this could be due to something particular in my setup, but I think adding `display: none` would be the proper way to handle this regardless. Let me know what you think!
