### ISSUE TITLE
Cant understand how to use the charging icon feature

### ISSUE THREAD

**Issue by danlun** [maxwroc/battery-state-card#40]
**Describe what is wrong**
With the YAML below (your example) I can't understand how the card can look as it does in your example. No sensors are mentioned in the YAML example but still senors and % show in the card example. Sorry, I do understand the other examples you have, but not this one.

**YAML configuration**
```yaml
# paste your card configuration here
- type: custom:battery-state-card
  title: "Charging indicators"
  entities:
    - entity: sensor.device_battery_numeric
      charging_state:
        entity_id: binary_sensor.device_charging
        state: "on"
    - entity: sensor.mi_roborock
      charging_state:
        state: "charging"
        icon: "mdi:flash"
        color: "yellow"

```**Screenshot**

**Version**
1.1.1

**Comment by maxwroc** [comment]
Yes you are right it can be confusing as the yaml doesn't match the screenshot in this case. I'll update it.

You can use icon override whenever you want and it should be applied when charging state is detected.

The case which I wanted to cover here (with `sensore.mi_robrock` entity) was that the sensor can produce "charging" state (string) when it's charging and numeric state otherwise. The problem is that when the state is not numeric the default icon is the "unknown" one:
![image](https://user-images.githubusercontent.com/8268674/80961546-0f3e2b00-8e03-11ea-9dab-c75b31bdaf58.png)
This way you can have a nice icon showing the battery level when not charging and meaningful icon when it is charging.
And of course when sensor state is a string we cannot show percentages and we show the state itself - in above case "Charging" (we upper-case first letter).

I hope it is clearer now

**Comment by danlun** [comment]
Yes it became better :-). And I do agree, if the screenshot is coherent with the YAML code it helps, at least us/me that is a beginner in the HA world.
