### ISSUE TITLE
FR: Allow the configuration of custom names

### ISSUE THREAD

**Issue by ChristophCaina** [maxwroc/battery-state-card#500]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to change the name of an entity within the card configuration (Instead of changing the global name of the entity)
This seems not to work.
![grafik](https://user-images.githubusercontent.com/26391061/197163699-ef718295-78d1-4b3f-9f05-ceb28d284def.png)

**Additional context**
none

**Comment by maxwroc** [comment]
This should work, if it doesn't then there must be a bug. I cannot check it at the moment

It looks like you want to get rid of the "Low Battery" string which is at the end of the name - instead of renaming all entities manually you can use `bulk_rename`
https://github.com/maxwroc/battery-state-card#entity-filtering-and-bulk-renaming

But as I said the `name` property should work and should override the original entity name. Will try to validate it on my HA
