### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by RoelG** [maxwroc/battery-state-card#569]
Hi

I installed via HACS and see that the resource is automatically added to my dashboard:
![image](https://github.com/maxwroc/battery-state-card/assets/3417359/4818b05e-ac86-4bd1-a286-216481199b96)

But how do I use the card? I cannot find it in the list between the existing cards:
![image](https://github.com/maxwroc/battery-state-card/assets/3417359/1edb1530-c297-44b6-a0fb-85b1c0b704bb)

Also tried using an entity card and overwrite the yaml code there with examples from the Readme, but when saving I don't see anything made visible?

**Comment by igorsantos07** [comment]
Have you tried writing a card manually with the readme examples? On the card filter, search for "manual" - that takes you to the usual YAML editor, and you can play around from there.

I wouldn't suggest closing the issue even if that works for you, since I _think_ the card should be available on the cards list, and it's not even in my case, where this card was installed ages ago, so there's no chance this is a cache problem.

**Comment by RoelG** [comment]
I got it working. I used this snippet from the readme, expecting all my batteries were automatically being shown:
`type: 'custom:battery-state-card'
title: Filters
sort_by_level: "asc"
bulk_rename:
  - from: "Battery Level" # simple string replace (note: "to" is not required if you want to remove string)
    to: "sensor"
  - from: "/\\s(temperature|temp)\\s/" # regular expression
    to: " temp. "
entities:
  # entities requiring additional properties can be added explicitly
  - entity: sensor.temp_outside_battery_numeric
    multiplier: 10
    name: "Outside temp. sensor"
filter:
  include: # filters for auto-adding
    - name: entity_id # entities which id ends with "_battery_level"
      value: "*_battery_level"
    - name: attributes.device_class # and entities which device_class attribute equals "battery"
      value: battery
  exclude: # filters for removing
    - name: state # exclude entities above 99% of battery level
      value: 99
      operator: ">"`

But the sensor.temp_outside_battery_numeric is unknown in my system of course, rendering the complete card empty...once I removed the entities part, it worked.
I'm not sure if the card should be visible in the list of existing cards in Home Assistant or not... I cannot make that up from the readme.

P.S. I'll update my initial question so it's more clear for everybody. My apologies.

**Comment by maxwroc** [comment]
> But the sensor.temp_outside_battery_numeric is unknown in my system of course, rendering the complete card empty...once I removed the entities part, it worked.

Yeah there is a bug in v2.X which breakes rendering when filters are used and there is an explicitly added entity which doesn't exist. Bug is fixed in v3 (not released yet)

> I'm not sure if the card should be visible in the list of existing cards in Home Assistant or not... I cannot make that up from the readme.

The versions < v3 won't be showing up on the list of available cards when you're trying to add it from the UI. This changes with v3

Closing this one as it seems that you have managed to solve your problem and the rest of the issues is known and fixed in v3.
