### ISSUE TITLE
Not clickable

### ISSUE THREAD

**Issue by 03397** [maxwroc/battery-state-card#8]
Using latest version.
You cannot click the batteries icon in order to see the graphs.

**Comment by maxwroc** [comment]
This is kid of by design for now. Since you can extract the battery state from attributes you wouldn't be able to see the graph tracking battery levels anyway.

I haven't added click handling as in my cases the battery level values were not changing too often so even if you have the graph for the state value it would be flat. Now I see that people sometimes use it for phone battery tracking and in such cases it makes more sense.

I'll add it

**Comment by 03397** [comment]
I thought this was done out of the box since it is just an entity
This is what I ave now without the card and out of the box.
![image](https://user-images.githubusercontent.com/6150853/80370755-730fa380-8899-11ea-958a-2bd639dff134.png)

**Comment by mdegat01** [comment]
Yea would like this as well.  There's also other use cases besides just phone battery.  Like for instance the native `more-info` pop-up has that gear in the top right corner that you can then use to customize the entity, its nice to be able to get to that from wherever to fix a name or something you don't like.

Also the popular plugin [browser-mod](https://github.com/thomasloven/hass-browser_mod) lets you replace the default more-info pop-up of an entity with the card of your choice.  So even though the graph isn't particularly helpful for most battery entities its still useful to be able to launch this pop-up in case someone wants to replace it with something more useful (like showing the control for that switch you're looking at battery of for example).

**Comment by SeLLeRoNe** [comment]
Please if you decide to implement it, make it a user-decision so that who doesn't want it (like me :D ) is not forced to have it ^^

**Comment by maxwroc** [comment]
Ok will add it in next update and yes it will be configurable :)

**Comment by maxwroc** [comment]
Will be available in v1.1.0
